---
# tasks/Amazon/rabbit.yml: Deploy RabbitMQ
# Specific to Amazon Linux

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: Configure RabbitMQ/RabbitMQ-erlang GPG keys in the RPM keyring
    rpm_key:
      key: "{{ item }}"
      state: present
    with_items:
      - https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
      - https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
    register: sensu_rabbitmq_import_key

  - name: Add RabbitMQ's repo
    yum_repository:
      name: rabbitmq
      description: rabbitmq
      baseurl: "https://dl.bintray.com/rabbitmq/rpm/rabbitmq-server/v3.7.x/el/{{ epel_version }}"
      gpgcheck: yes
      gpgkey: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
      repo_gpgcheck: no

  - name: Add RabbitMQ's Erlang repo
    yum_repository:
      name: rabbitmq-erlang
      description: rabbitmq-erlang
      baseurl: "https://dl.bintray.com/rabbitmq/rpm/erlang/19/el/{{ epel_version }}"
      gpgcheck: yes
      gpgkey: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
      repo_gpgcheck: no

  # HACK: https://github.com/ansible/ansible/issues/20711#issuecomment-306260869
  # Can be removed once we're running w/ a version of Ansible that has https://github.com/ansible/ansible/pull/35989
  - name: Make yum cache to import GPG keys
    command: "yum -q makecache -y --disablerepo='*' --enablerepo='{{ item }}'"
    args:
      warn: false
    when: sensu_rabbitmq_import_key.changed
    with_items:
      - rabbitmq
      - rabbitmq-erlang

  # Hard dependency for rabbitmq-server, however, typically comes from EPEL, so
  # we simply install it here, as we purposely disable epel when installing rabbitmq
  # causing dependency issues during installs
  - name: Ensure socat is installed
    yum:
      name: socat
      state: present

  - name: Ensure Erlang & RabbitMQ are installed
    yum:
      name:
        - erlang
        - rabbitmq-server
      state: present
      enablerepo: rabbitmq,rabbitmq-erlang
      disablerepo: epel
