---
group: travis_lts
services: docker
addons:
  apt:
    packages:
      - docker-ce
install:
  - pip install pipenv
  - pipenv install --two --dev
script:
  - pipenv run molecule test --scenario-name default --driver-name docker --destroy always

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
