site_name: Ansible Sensu
site_url: https://galaxy.ansible.com/cmacrae/sensu/
repo_url: https://github.com/cmacrae/ansible-sensu/
site_description: An Ansible role to deploy a fully dynamic Sensu stack!
site_author: Calum MacRae

theme: flatly
pages:
  - Home: index.md
  - Usage:
    - Role Variables: role_variables.md
    - Example Infrastructure Layout: example_infra.md
    - Deploy The Stack to a Single Node: single_master.md
    - Custom Client Configuration: custom_client_config.md
    - Deployment - Handlers/Filters/Mutators: deploy_plugins.md
    - Remote Plugin Deployment: remote_plugins.md
    - Sensitive Information in Version Control: sensitive_info.md
    - Testing: testing.md
  - Conventions:
    - Dynamic Data Store: dynamic_data.md
    - Dynamic Check Deployment: dynamic_checks.md
  - About:
    - A few words from the author: afewwords.md
    - License: license.md
