---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: False
platforms:
  - name: debian-8
    image: dokken/debian-8
    command: /lib/systemd/systemd
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian-9
    image: dokken/debian-9
    command: /lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu-14.04
    image: dokken/ubuntu-14.04
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
  - name: ubuntu-16.04
    image: dokken/ubuntu-16.04
    command: /bin/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#  - name: ubuntu-18.04
#    image: dokken/ubuntu-18.04
#    command: /bin/systemd
#    capabilities:
#      - SYS_ADMIN
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos-6
    image: dokken/centos-6
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
  - name: centos-7
    image: dokken/centos-7
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#  - name: fedora-26
#    image: dokken/fedora-26
#    command: /usr/lib/systemd/systemd
#    capabilities:
#      - SYS_ADMIN
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#  - name: fedora-27
#    image: dokken/fedora-27
#    command: /usr/lib/systemd/systemd
#    capabilities:
#      - SYS_ADMIN
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#  - name: fedora-28
#    image: dokken/fedora-latest
#    command: /usr/lib/systemd/systemd
#    capabilities:
#      - SYS_ADMIN
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#  - name: amazonlinux-1
#    image: dokken/amazonlinux
#    command: /sbin/init
#    capabilities:
#      - SYS_ADMIN
#  - name: amazonlinux-2
#    image: dokken/amazonlinux-2
#    command: /usr/lib/systemd/systemd
#    capabilities:
#      - SYS_ADMIN
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: False
  inventory:
    group_vars:
      all:
        sensu_master: true
        sensu_include_dashboard: true
        rabbitmq_server: true
        redis_server: true
        rabbitmq_host: "{{ ansible_hostname }}"
        redis_host: "{{ ansible_hostname }}"
        sensu_api_host: "{{ ansible_hostname }}"
        ansible_default_ipv4:
          address: 127.0.0.1
    host_vars:
      debian-8:
        inspec_download_url: https://packages.chef.io/files/stable/inspec/2.1.68/ubuntu/16.04/inspec_2.1.68-1_amd64.deb
        inspec_download_sha256sum: bb411271af5275c26f0129a61230a1080d22a6e99eb0f1b52223ee9d55827375
      debian-9:
        inspec_download_url: https://packages.chef.io/files/stable/inspec/2.1.68/ubuntu/16.04/inspec_2.1.68-1_amd64.deb
        inspec_download_sha256sum: bb411271af5275c26f0129a61230a1080d22a6e99eb0f1b52223ee9d55827375
      ubuntu-14.04:
        inspec_download_url: https://packages.chef.io/files/stable/inspec/2.1.68/ubuntu/14.04/inspec_2.1.68-1_amd64.deb
        inspec_download_sha256sum: bb411271af5275c26f0129a61230a1080d22a6e99eb0f1b52223ee9d55827375
      ubuntu-16.04:
        inspec_download_url: https://packages.chef.io/files/stable/inspec/2.1.68/ubuntu/16.04/inspec_2.1.68-1_amd64.deb
        inspec_download_sha256sum: bb411271af5275c26f0129a61230a1080d22a6e99eb0f1b52223ee9d55827375
      centos-6:
        inspec_download_url: https://packages.chef.io/files/stable/inspec/2.1.68/el/6/inspec-2.1.68-1.el6.x86_64.rpm
        inspec_download_sha256sum: a62bc8d8ea803a72b7e834f5993c1d9eab50539293365a067cd29736daeb3fea
      centos-7:
        inspec_download_url: https://packages.chef.io/files/stable/inspec/2.1.68/el/7/inspec-2.1.68-1.el7.x86_64.rpm
        inspec_download_sha256sum: 54fb2aab023a228c8f622653daabed14f2345780ec978670dbd262a63ad06fe9
scenario:
  name: default
verifier:
  name: inspec
  lint:
    name: rubocop
    enabled: true
