---
# tasks/Debian/redis.yml: Deploy Redis
# Specific to Debian

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: Ensure Redis is installed
    apt:
      name: "{{ sensu_redis_pkg_name }}"
      state: "{{ sensu_redis_pkg_state }}"
      update_cache: true

  - name: Ensure Redis binds to accessible IP
    lineinfile:
      dest: /etc/redis/redis.conf
      regexp: '^bind'
      line: 'bind 0.0.0.0'
    notify: restart redis service

  - meta: flush_handlers
