---
# tasks/SmartOS/redis.yml: Deploy Redis
# Specific to Ubuntu

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: Ensure Redis is installed
    pkgin: name=redis state={{ sensu_redis_pkg_state }}
