---
# tasks/CentOS/main.yml: CentOS specific set-up
# This takes care of base prerequisites for CentOS

  - include_vars: "{{ ansible_distribution }}.yml"

  - name: Ensure the Sensu Core Yum repo is present
    yum_repository:
      name: sensu
      description: The Sensu Core yum repository
      baseurl: "{{ sensu_yum_repo_url }}"
      gpgcheck: no
      enabled: yes

  - name: Ensure Sensu is installed
    yum:
      name: "{{sensu_package }}-{{sensu_pkg_version}}"
      state: "{{ sensu_pkg_state }}"

